### ISSUE TITLE
Hitting OOM issues when deleting large(ish) datasets

### ISSUE THREAD

**Issue by rdalzell** [vaticle/typedb#6323]
Please replace every line in curly brackets { like this } with an appropriate answer, and remove this line.

## Description

When attempting to delete a  large dataset the grakn node repeatedly OOMs.

The dataset consists of 230K relations;

```
crimgraph-mvp::data::write> match $a isa dependency; get $a; count;
232215
crimgraph-mvp::data::write> match $a isa dependency; delete $a isa dependency;
Killed
```

## Environment

1. Kubernetes deloyment
2. 2.0.2 docker image
3. Using console verson: 2.0.1
4. Kubernetes pod spec;

```
spec:
      containers:
        - name: grakn-core
          imagePullPolicy: IfNotPresent
          image: hub.tess.io/eccs/grakn:2.0.2
          resources:
            # need more cpu upon initialization, therefore burstable class
            requests:
              cpu: 2000m
              memory: 6000Mi
            limits:
              cpu: 2000m
              memory: 4000Mi
          command:
            - /bin/bash
            - -c
            - '/opt/grakn-core-all-linux/grakn server --data=/mnt/data/ '
          ports:
            - containerPort: 1729
              name: client-port
            - containerPort: 1730
              name: server-port
          volumeMounts:
            - name: grakn-data
              mountPath: /mnt/data
      volumes:
      - name: grakn-data
        persistentVolumeClaim:
          claimName: grakn-data
```

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. match $a isa dependency; delete $a isa dependency;

## Actual Output

OOM, node restarts.
